config/routes.rb
Rails.application.routes.draw do

   root 'deals#index'

   get '/signup' => 'users#new'
   post '/users' => 'users#create'
   get '/users/:id' => 'users#show',as: :user

   get "/login" => 'sessions#new'
   post '/sessions' => 'sessions#create'
   get "/logout" => 'sessions#delete'



  #########################################################
  # The "Golden 7" for accessing the "deals" resource

  resources :deals do
    resources :comments, only: [:new, :create]
    resources :likes, only: [:create]
    resources :bookmarks, only: [:create, :delete]
  end
  # get '/deals/new' => 'deals#new', as: 'new_deal'
  # post '/deals' => 'deals#create', as: 'deals'

  # get '/deals' => 'deals#index'
  # get '/deals/:id' => 'deals#show', as: 'deal'

  # get '/deals/:id/edit' => 'deals#edit', as: 'edit_deal'
  # patch '/deals/:id' => 'deals#update'

  # delete '/deals/:id' => 'deals#destroy'






end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :deal
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :deal
	belongs_to :user
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	has_many :items, :dependent => :delete_all
	has_many :likes, :dependent => :delete_all
	has_many :comments, :dependent => :delete_all
	has_many :bookmarks, :dependent => :delete_all
	has_many :deal_price, :dependent => :delete_all
	has_many :users, :through => :bookmarks

	validates_presence_of :title
	validates_presence_of :title_picture
	validates_presence_of :description
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :deal
	belongs_to :user
end

app/models/session.rb
class Session < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	
	has_many :likes, :dependent => :delete_all
	has_many :comments, :dependent => :delete_all
	has_many :bookmarks, :dependent => :delete_all
	has_many :deals, :through => :bookmarks

	validates :name, :presence=> true, :uniqueness => true, :allow_nil =>false
	validates :email, :presence=> true, :uniqueness => true, :allow_nil =>false
	validates :password, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@deal=Deal.find_by(id:params[:deal_id])
  	@comment=Comment.new
  end

  def create
  	@deal=Deal.find_by(id:params[:deal_id])
    @comment = Comment.new
    @comment.text = params[:comment]
    @comment.deal_id=params[:deal_id]

    if session[:user_id].blank?
      @comment.user_id=nil
    else
      @comment.user_id=session[:user_id]
    end
   
    if @comment.save
      redirect_to deal_url(@deal.id)
    else
      render 'new'
    end
    
  end

end

app/controllers/concerns/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  def create
    @bookmark=Bookmark.new
    @bookmark.deal_id=params[:deal_id]
    if session[:user_id].blank?
      redirect_to root_url, notice: "You must login to do this action"
    else
      @bookmark.user_id=session[:user_id]
      if Bookmark.exists?(:user_id => @bookmark.user_id, :deal_id => @bookmark.deal_id)
        redirect_to root_url, notice: "You have already bookmarked this deal"
      else
        @bookmark.save
        redirect_to root_url, notice: "You just booked marked a deal"
      end
    end
    
  end

  def delete

  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :require_user, :only => [:new, :edit, :update, :destroy]
  before_action :find_deal, :only => [:show, :edit, :update, :destroy]
  def find_deal
    @deal = Deal.find_by(id: params["id"])
  end


  def require_user
    if session[:user_id].blank?
      redirect_to root_url, notice: "You need to login to do that."
    end
  end

  def index
    if params["keyword"].present?
      @deals=Deal.where("lower(title) LIKE ? OR lower(description) LIKE ?","%#{params[:keyword]}%".downcase,"%#{params[:keyword]}%").limit(100)
    else
      @deals=Deal.all.limit(100)
    end

    @deals=@deals.order('title asc').page(params[:page]).per(5)
  end

  def show
    if @deal == nil
      redirect_to deals_url, notice: "Deal not found."
    else
      cookies["deal_history_id"] ||=""
      if !cookies["deal_history_id"].include?(@deal.id.to_s)
        cookies["deal_history_id"] += "#{@deal.id} "
      end
    end
  end

  def new
    @deal=Deal.new
  end

  def create
    d=params.require(:deal).permit(:title, :title_picture, :purchase_link, :category, :description)
    @deal=Deal.new(d)

    # @deal = Deal.new
    # @deal.title = params[:title]
    # @deal.title_picture = params[:title_picture]
    # @deal.purchase_link = params[:purchase_link]
    # @deal.category = params[:category]
    # @deal.description = params[:description]
    @deal.created_at = DateTime.now
    if @deal.save
      redirect_to deals_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    d=params.require(:deal).permit(:title, :title_picture, :purchase_link, :category, :description)
    @deal.title = params[:deal][:title]
    @deal.title_picture = params[:deal][:title_picture]
    @deal.purchase_link = params[:deal][:purchase_link]
    @deal.category = params[:deal][:category]
    @deal.description = params[:deal][:description]
    if @deal.save
      redirect_to deals_url
    else
      render 'edit'
    end
  end

  def destroy
    @deal = Deal.find_by(id: params["id"])
    @deal.delete
    redirect_to deals_url
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @like=Like.new
    @like.deal_id=params[:deal_id]
    if session[:user_id].blank?
      redirect_to root_url, notice: "You must login to do this action"
    else
      @like.user_id=session[:user_id]
      @like.like_value=1
      if Like.exists?(:user_id => @like.user_id, :deal_id => @like.deal_id)
        redirect_to root_url, notice: "You have already liked this deal"
      else
        @like.save
        redirect_to root_url, notice: "Thanks for Liking the deal"
      end
    end
    
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user
      if user.authenticate(params[:password])
        session["user_id"] = user.id
        redirect_to root_url, notice: "Welcome back!"
      else
        redirect_to root_url, notice: "Unknown password."
      end
    else
      redirect_to root_url, notice: "Unknown email."
    end
  end

  def delete
    if session["user_id"].present?
      
      session.delete "user_id"
      cookies.delete "deal_history_id"
    else
      redirect_to root_url, notice:"Logout with a problem!"
    end
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authorize, only: [:show]

	def authorize
		@user=User.find_by(id:params[:id])
		if @user.blank? || session[:user_id] != @user.id
			redirect_to root_url, notice: "You don't have permission to access this page"
		end
	end
	
	def new
		@user=User.new
	end

	def show

	end

	def create
		@user=User.new(email:params[:email], name:params[:name], password: params[:password])
		if @user.save
			# UserMailer.welcome_email(@user).deliver_later
			redirect_to root_url, notice: "Thanks for signing up!"
		else
			render 'new'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
  <ul class="errors">
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_tag deal_comments_url(@deal) do %>
  <div>
    <label for="comment">Comment:</label>
    <input size="80" name="comment" id="comment">
  </div>

  <input type="submit" name="commit" value="Add Comment">

<% end %>

app/views/deals/edit.html.erb
<% if @deal.errors.any? %>
  <ul class="errors">
    <% @deal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @deal do |form| %>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title, size: 120 , value: @deal.title, placeholder: "Example Cardcash: Extra 5% Off Movie Gift Cards: Fandango $25 GC" %>
  </div>

  <div>
    <%= form.label :title_picture%>
    <%= form.text_field :title_picture, size: 120, value: @deal.title_picture %>
  </div>

  <div>
    <%= form.label :purchase_link%>
    <%= form.text_field :purchase_link, size: 120, value: @deal.purchase_link%>
  </div>

  <div>
    <%= form.label :category%>
    <%= form.text_field :category, size: 120, value: @deal.category %>
  </div>

  <div>
    <%= form.label :description%>
    <%= form.text_field :description, size: 120, value: @deal.description %>
  </div>

  <%= form.submit %>
  
<% end %>

app/views/deals/index.html.erb
<% if cookies[:deal_history_id].present? %>
  <h3>Deals you viewed</h3>

    <% cookies[:deal_history_id].split.last(7).each do |deal_id| %>
      <% if Deal.find_by(id: deal_id).title_picture.present? %>
        <%= link_to image_tag(Deal.find_by(id: deal_id).title_picture),deal_url(Deal.find_by(id:deal_id)) %>
      <% end %>
    <% end %>
<% end %>


<%= form_tag deals_url, :method => "get" do %>

  <%= text_field_tag :keyword %>
  <%= submit_tag "Search" %>

<% end %>


<% if session[:user_id].present? %>
  <p><%= link_to "Add a New Deal", new_deal_url %></p>
<% end %>

<p><%= @deals.count %> deals shown</p>
<%= paginate @deals%>


<table class="table table-striped">
  <tr>
    <th>Hot Deals</th>
    <th>Title</th>
    <th>Category</th>
    <th>Created at</th>
    <th></th>
  </tr>
  <% @deals.each do |deal| %>
    <tr>
      <td><%= image_tag(deal.title_picture) %></td>
      <td><%= link_to deal.title, deal_url(deal.id) %> <br>
        <% if deal.purchase_link.present? %>
        <%= link_to "Purchase", deal.purchase_link %>
        <% end %>
        <span class="glyphicon glyphicon-thumbs-up"> </span>
        <%= link_to "Like", deal_likes_url(deal.id), method: :post%>
        <span>(<%= deal.likes.count %>)</span>
        <span class="glyphicon glyphicon-bookmark"></span>
        <%= link_to "Bookmark", deal_bookmarks_url(deal.id),method: :post %>
       <br>
        <% if deal.description!=nil %>
          <%= deal.description.html_safe %>
        <% end %>

      </td>
      <td><%= deal.category %> </td>
      <td><%= deal.created_at %>
        <br> <%= link_to "Edit...", "/deals/#{deal.id}/edit" %>
        <br> <%= link_to "Delete", "/deals/#{deal.id}", :method => 'delete' %>

      </td>

      
    </tr>
  <% end %>

</table>

app/views/deals/new.html.erb
<% if @deal.errors.any? %>
  <ul class="errors">
    <% @deal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @deal do |form| %>
  <div>
    <%= form.label :title%>
    <%= form.text_field :title, size: 120 , value: @deal.title, placeholder: "Example Cardcash: Extra 5% Off Movie Gift Cards: Fandango $25 GC" %>
  </div>

  <div>
    <%= form.label :title_picture%>
    <%= form.text_field :title_picture, size: 120, value: @deal.title_picture %>
  </div>

  <div>
    <%= form.label :purchase_link%>
    <%= form.text_field :purchase_link, size: 120, value: @deal.purchase_link%>
  </div>

  <div>
    <%= form.label :category%>
    <%= form.text_field :category, size: 120, value: @deal.category %>
  </div>

  <div>
    <%= form.label :description%>
    <%= form.text_field :description, size: 120, value: @deal.description %>
  </div>

  <%= form.submit %>
  
<% end %>

app/views/deals/show.html.erb
<h2><%= @deal.title %></h2>


<% if @deal.purchase_link.present? %>
  <%= link_to "Purchase", @deal.purchase_link %>
<% end %>
<span class="glyphicon glyphicon-thumbs-up"> </span>
<%= link_to "Like", deal_likes_url(@deal.id), method: :post%>
<span>(<%= @deal.likes.count %>)</span>
<span class="glyphicon glyphicon-bookmark"></span>
<%= link_to "Bookmark", deal_bookmarks_url(@deal.id),method: :post %>
<br>

<p>
  
	 <% if @deal.description!=nil %>
        <%= @deal.description.html_safe %>
     <% end %>
</p>

<%= image_tag @deal.title_picture %>
<br>
<h3>
<span>Comments  </span>
<span class="carat">›</span>
<span ><%= link_to "Add Comments", new_deal_comment_url(@deal) %></span>
</h3>



<% if @deal.comments.present? %>
   <% @deal.comments.each do |comment| %>
   	 <div class="alert alert-info">
   	 	<% if comment.user.present? %>
   	   		<p><%= comment.created_at  %> by <%= comment.user.name%></p>
   	   	<% else %>
   	   		<p><%= comment.created_at  %> by Anonymous</p>
   	   	<% end %>
       <p><%= comment.text %></p>
     </div>
   <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DealNow</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <h1><%= link_to "Deals Here", "/" %>

      <small><%= link_to "Hot Deals", '/deals' %></small>
      <div class="pull-right">
        <% if session["user_id"].present? %>
          <small>Hello, <%= User.find_by(id: session["user_id"]).name %></small>
          <small><%= link_to "My Account",user_url(User.find_by(id: session["user_id"])) %> </small>
          <small><%= link_to "Sign Out", '/logout' %></small>
        
        <% else %>
          <small><%= link_to "Sign Up", '/signup' %></small>
          <small><%= link_to "Sign In", '/login' %></small>

        <% end %>
      </div>

    </h1>

    <% if notice.present? %>
      <div class="alert alert-info"%>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/users/new.html.erb
<h3>Sign Up</h3>
<% if @user.errors.any? %>
  <ul class="errors">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_tag "/users" do %>

  <p>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
  </p>

  <p>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
  </p>

  <p>
    <%= label_tag :password %>
    <%= text_field_tag :password %>
  </p>

  <%= submit_tag "Sign Up!" %>
<% end %>

app/views/users/show.html.erb
<h2><span class="label label-default">My Account</span></h2>

<h3>
<%= @user.name%> since <%= @user.created_at %>
</h3>

<h2><span class="label label-default">Bookmarks</span></h2>

<h3>
	<ul>
		<% @user.deals.each do |deal|%>
			<li><%= link_to deal.title, deal_url(deal) %></li>
		<% end %>
	</ul>
</h3>